### ISSUE TITLE
Api for pet finder has changed

### ISSUE THREAD

**Issue by kumaranando85** [btholt/petfinder-client#1]
Hi Brian,
It seems that the pet finder api has changed and your method is returning undefined when required and also the key passed to the breed.list method is coming out to be undefined can you please suggest anything.
Here is the url getting generated by the petfinder
```
http://api.petfinder.com/breed.list?key=undefined&format=json&animal=dog&callback=jsonp_e7rzr789d2zaw95
```
Your help would be highly appreciable.

Thanks

**Comment by usrnull** [comment]
@kumaranando85 Any luck with that?

**Comment by kumaranando85** [comment]
Hi Aasim,
You just directly put the credentials in your file and not use process.env
altogether.
It worked for me.

Thanks,
Kumar

**Comment by u5r0** [comment]
Yeah, I thought of that too. But I tried to switch `package.json` of the `a03f523888` commit with mine temporarily then I ran `npm install` on it and it worked. Then I switched back to my `package.json` and ran `npm install` on it and it surprisingly worked too :smile:. I have no idea why or how :joy: 

That's when I decided to delete my comment :smiley: 
Thanks for your time :smiley:

**Comment by AIndoria** [comment]
I know that you fixed it, but for anyone in future reading this and not wanting to waste time (Like I wasted about an hour looking around for solutions), restart your VSCode after installing ESLint, and then you can restart your server. This package won't work without doing t hat.
